### ISSUE TITLE
Test CLI Arg Parsing and Handle Errors.

### ISSUE THREAD

**Issue by collinarnett** [collinarnett/PersonalGamification#19]
Currently we add all the cli args but we need to test them for user error handling.

**Comment by abene86** [comment]
Improvement: I found using a regular expression for formating a pattern for the arguments would help us avoid typecasting errors and the user entering the wrong input. It also makes it easier for us so we can expect a correctly formatted input for map split in parseTask. 
Status: The idea is there I just keep getting an error when building it, so I will play with to see what is wrong.

**Comment by abene86** [comment]
Sample edge cases:
1) pg add  no arguments
2) pg add 122313i3i1o313io13i
3) pg add nami=hello, description=world, effort=12, due=2022-3-22
4) pg add namehellodescriptionworldeffort122022-3-22
5) pg add nami=hello, description=world, effort=12, due=hello

**Comment by abene86** [comment]
Improvement: I was able to fix the compile error and was able to test sample edge cases whether the regular expression pattern produces the correct true or false outcome. What is remaining is to test the parsing as a whole and to add on regular expression which account for the space between the ',' and the next word. Here is sample of the regx ("name=[a-zA-z]+,description=[a-zA-Z]+,effort=[0-9],due=(\\d{4})-([01][0-9])-([012][0-9])").

**Comment by collinarnett** [comment]
Just FYI you can format using markdown syntax on Github https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by abene86** [comment]
Improvement: I was able to write tests using scala test and running, Metals. I also have a better understanding of how the command works. The only problem is testing specifically from string passing to parsing a task.

**Comment by collinarnett** [comment]
Things todo with Tasks:

1. Refactor parser into a singleton object. This will make testing easier because we can import this object and use it elsewhere.
2. Refactor argument validation to not use regex. 
3. Refactor type checking to be more scala friendly and robust. Currently we just typecast and hope for the best but this is not okay because we could have runtime errors. It’s better to have compile time errors. 
4. Make liberal use of Some Option and None while parsing arguments so the downstream program can have expectations of non-null parameters.

**Comment by collinarnett** [comment]
Split this work between me and @abene86 
I will work on 
1,3
@abene86 Will work on the rest.
Please merge into the task branch and we can then work on the refactoring from there.

**Comment by abene86** [comment]
```scala
def runTaskCommands(command: String) =
  command match 
    case "--ls"=> println(" call ls")
    case "--add"=> println(" call add")
    case "--delete" => println("call delete")
    case "--adjust" =>println("call adjust")
    case "--completed" => println("call completed")

def runPlayerCommands(command:String) =
    command match
    case "--create" => println("call createCharacter")
    case "--delete" => println("call deleteCharacter")
    case "--Story" => println("call  readStoryCharacter")


@main def main(args: String*) =
    if(args.size >= 3)
      val mode = args(1)
      if(mode.equalsIgnoreCase("task"))
        runTaskCommands(args(2))
      else if(mode.equalsIgnoreCase("player"))
        println("runPlayerCommands")
      else  
        println("Wrong Mode Please Choose bewteen Task and Player")
    else
      println("Please Enter the correct number of arguments")
```

**Comment by collinarnett** [comment]
This method side steps scopt. Scopt is our chosen parser and we should operate within it's paradigm.

**Comment by collinarnett** [comment]
@abene86 I ran the tests in sbt and the error messages don't really help the user.

```
Error: Missing value after --add
pg 0.1.0 https://github.com/collinarnett/PersonalGamification
Usage: pg [task]

Command: task [options]
Manage tasks.
  --add <value>           Example: pg task --add name=hello,description=world,effort=12,due=2020-02-12
Error: Option --add failed when given 'name=hello, description=world, effort=12, due=2022-3-22'. key not found: description
pg 0.1.0 https://github.com/collinarnett/PersonalGamification
Usage: pg [task]

Command: task [options]
Manage tasks.
  --add <value>           Example: pg task --add name=hello,description=world,effort=12,due=2020-02-12
Error: Option --add failed when given 'aaaaaadkajkdjkajdkajdkajkdjkajdka111'. key not found: name
pg 0.1.0 https://github.com/collinarnett/PersonalGamification
Usage: pg [task]

Command: task [options]
Manage tasks.
  --add <value>           Example: pg task --add name=hello,description=world,effort=12,due=2020-02-12
Error: Option --add failed when given 'namehellodescriptionworldeffort122022-3-22'. key not found: name
pg 0.1.0 https://github.com/collinarnett/PersonalGamification
Usage: pg [task]

Command: task [options]
Manage tasks.
  --add <value>           Example: pg task --add name=hello,description=world,effort=12,due=2020-02-12
[info] PersonalGamificationSpec:
[info] - should take Properly format args and create a task object
[info] Run completed in 214 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 4 s, completed Mar 30, 2022, 12:42:00 PM
```
How does the user pinpoint their cli args with errors like `key not found`? Any error with the loading of the of add args should explain how to format their args correctly.

**Comment by collinarnett** [comment]
`name=String,description=String,effort=Integer,due="yyyy-mm-dd"`

"Reminder: Arguments are delimited by a comma only"

**Comment by collinarnett** [comment]
@abene86 I think once you finish this last change this issue will be done. Make a PR into tasks with this latest change and reference this issue.

**Comment by collinarnett** [comment]
#22 Finishes this issue.
